server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

application:
  kafka:
    topic: credit-applications
  rabbitmq:
    queue: credit-responses
    exchange: credit-exchange
    routing-key: credit.response